# Generated by Django 3.0.3 on 2020-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyRunPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=2)),
                ('time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('units', models.CharField(choices=[('KM', 'Kilometres'), ('MI', 'Miles')], default='KM', max_length=2)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
