# Generated by Django 3.0.3 on 2020-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyrunplan',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='easyrunplan',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
