# Generated by Django 3.0.3 on 2020-02-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20200213_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyrunplan',
            name='time',
        ),
    ]
