# Generated by Django 3.0.3 on 2020-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtype', models.CharField(choices=[('EASY', 'Easy run'), ('ENDURANCE', 'Endurance run'), ('TEMPO', 'Tempo run'), ('INTERVALS', 'Interval run'), ('UNCATEGORISED', 'Uncagetorised run')], default='UNCATEGORISED', max_length=13)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtype', models.CharField(choices=[('EASY', 'Easy run'), ('ENDURANCE', 'Endurance run'), ('TEMPO', 'Tempo run'), ('INTERVALS', 'Interval run'), ('UNCATEGORISED', 'Uncagetorised run')], default='UNCATEGORISED', max_length=13)),
                ('date', models.DateField()),
                ('units', models.CharField(choices=[('KM', 'Kilometres'), ('MI', 'Miles')], default='KM', max_length=2)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pace', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_HR', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RunLog',
        ),
        migrations.DeleteModel(
            name='RunPlan',
        ),
        migrations.RemoveField(
            model_name='race',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='race',
            name='racetype',
        ),
        migrations.RemoveField(
            model_name='race',
            name='units',
        ),
    ]
